name: expandtesting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Symfony
        run: |
          cd apache-jmeter-5.6.3/bin

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: expandtesting.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
          plugins: "jpgc-standard"

      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
